# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LogReg', '0004_auto_20170127_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travelers', models.ManyToManyField(to='LogReg.User')),
            ],
        ),
    ]
