# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20170127_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='enddate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='trip',
            name='startdate',
            field=models.DateTimeField(default=None),
        ),
    ]
