# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0004_auto_20170127_1445'),
        ('exam', '0003_auto_20170127_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LogReg.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
